language: go

go:
  - 1.13.x

services:
  - docker

jobs:
  include:
    - stage: Unit Test
      name: "Unit Test"
      script:
        - make test

    - stage: Build and Deploy
      name: "kind"
      addons:
        snaps:
        - name: kubectl
          confinement: classic
      script:
        -  GO111MODULE=on go get sigs.k8s.io/kind
        -  ./scripts/kind.sh
        -  docker build -t localhost:5000/druid-io:latest .
        -  docker push localhost:5000/druid-io:latest
        -  kubectl get nodes
