language: go

go:
  - 1.13.x

services:
  - docker

jobs:
  include:
    - stage: Build and Test
      name: "build"
      script:
        - docker build -t druidio/druid-operator:testversion .
        - docker tag  druidio/druid-operator:testversion localhost:5000/druid-io:latest

    - stage: Build and Test
      name: "kind"
      script:
        -  GO111MODULE=on go get sigs.k8s.io/kind
        - ./scripts/kind.sh
        - docker push localhost:5000/druid-io:latest

    - stage: Deploy
      addons:
        snaps:
        - name: kubectl
          confinement: classic
      script:
        - kubectl get nodes
