name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone the code
        uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
          go-version: "1.19"
    - name: Remove pre-installed kustomize
      run: sudo rm -f /usr/local/bin/kustomize
    - name: Perform the test
      run: make test
    - name: Build the Docker image
      run: docker build . -t druidio/druid-operator:$(date +%s)
